const packages = [
    {
      id: 1,
      title: 'COMPLETE BLOOD COUNT; CBC',
      parameters: '20 Parameter(s) Covered',
      price: '₹ 350',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 2,
      title: 'HbA1c; GLYCOSYLATED HEMOGLOBIN',
      parameters: '2 Parameter(s) Covered',
      price: '₹ 440',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 3,
      title: 'URINE EXAMINATION, ROUTINE; URINE, R/E',
      parameters: '16 Parameter(s) Covered',
      price: '₹ 120',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 4,
      title: 'GLUCOSE, FASTING (F) AND POST MEAL (PP), 2 HOURS',
      parameters: '2 Parameter(s) Covered',
      price: '₹ 150',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 5,
      title: 'THYROID PROFILE, TOTAL',
      parameters: '3 Parameter(s) Covered',
      price: '₹ 550',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 6,
      title: 'WELLNESS REPORT',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 250',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 7,
      title: 'GLUCOSE, FASTING (F)',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 80',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 8,
      title: 'SWASTH SUPER -2',
      parameters: '55 Parameter(s) Covered',
      price: '₹ 3370 (₹ 2350)',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 9,
      title: 'SWASTH SUPER -4',
      parameters: '57 Parameter(s) Covered',
      price: '₹ 6120 (₹ 4050)',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 10,
      title: 'LIVER PANEL 1; LFT',
      parameters: '11 Parameter(s) Covered',
      price: '₹ 800',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 11,
      title: 'LIPID PROFILE, BASIC',
      parameters: '6 Parameter(s) Covered',
      price: '₹ 1000',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 12,
      title: 'KIDNEY PANEL; KFT',
      parameters: '16 Parameter(s) Covered',
      price: '₹ 850',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 13,
      title: 'LIVER & KIDNEY PANEL',
      parameters: '23 Parameter(s) Covered',
      price: '₹ 1550',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 14,
      title: 'TSH (THYROID STIMULATING HORMONE), ULTRASENSITIVE',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 380',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 15,
      title: 'DENGUE FEVER NS1 ANTIGEN, EIA',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 600',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 16,
      title: 'C-REACTIVE PROTEIN; CRP',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 440',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 17,
      title: 'HEMOGLOBIN; Hb',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 110',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 18,
      title: 'CULTURE, URINE',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 815',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 19,
      title: 'CREATININE, SERUM',
      parameters: '3 Parameter(s) Covered',
      price: '₹ 150',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 20,
      title: 'VITAMIN D 25 - HYDROXY',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 1550',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 21,
      title: 'URIC ACID, SERUM',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 160',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 22,
      title: 'ESR; ERYTHROCYTE SEDIMENTATION RATE',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 140',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 23,
      title: 'Lipid Profile, Screen',
      parameters: '6 Parameter(s) Covered',
      price: '₹ 400',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
    {
      id: 24,
      title: 'VITAMIN B12; CYANOCOBALAMIN',
      parameters: '1 Parameter(s) Covered',
      price: '₹ 1200',
      homeCollection: 'Home Collection',
      labVisit: 'Lab Visit',
      compare: 'Compare',
    },
  ];

  export default packages;